build: Scripts for building and cleaning automatically
Signed-off-by: Fernando Mateos Gomez <fernandomateos.fermatgom@gmail.com>

diff --git a/utils/clean b/utils/clean
--- a/utils/clean
+++ b/utils/clean
@@ -1,38 +1,31 @@
 #!/bin/sh
 
-log_error() {
-    printf "Error: %s\n" "$1" >&2
-    exit 1
-}
-
 if [ ! -d ".git" ]; then
-    log_error "This script must be run at the root of a Git repository."
+    printf "[%s]> .git|This script must be run at the root of a Git repository.\n" "$(date)" >&2
+    exit 1
 fi
-
-recursive_js_cleanup() {
-    find . -type f -name '*.js' -delete &
-}
 
 current_dir=$(pwd)
 
-echo "Cleaning Frontend folder on $current_dir/app"
-cd app/ || log_error "Unable to change directory to 'app/'"
+echo "FRONTEND[$(date)]> Cleaning Frontend folder on $current_dir/app"
+cd app/ || { printf "FRONTEND[%s]> cd app|Unable to change directory to 'app/'\n" "$(date)" >&2; exit 1; }
 
 rm -rf node_modules
 rm -rf dist
-echo "Cleaning Frontend folder on $current_dir/app Success"
+echo "FRONTEND[$(date)]> Cleaning Frontend folder on $current_dir/app Success"
 
-cd "$current_dir" || log_error "Unable to change back to the original directory"
+cd "$current_dir" || { printf "FRONTEND[%s]> cd \"$current_dir\"|Unable to change back to the original directory\n" "$(date)" >&2; exit 1; }
 
-echo "Cleaning Backend versions on $current_dir/api"
-cd api/ || log_error "Unable to change directory to 'api/'"
+echo "BACKEND[$(date)]> Cleaning Backend versions on $current_dir/api"
+cd api/ || { printf "BACKEND[%s]> cd api/|Unable to change directory to 'api/'\n" "$(date)" >&2; exit 1; }
 
 for folder in v[0-9]*; do
     cd "$folder" || continue
-    echo "Version $folder cleaning"
+    echo "BACKEND[$(date)]> Version $folder cleaning"
     rm -rf node_modules
-    recursive_js_cleanup
-    echo "Version $folder cleaning Success"
+    find . -type f -name '*.js' -delete
+    echo "BACKEND[$(date)]> Version $folder cleaning Success"
     cd ..
 done
 
+exit 0
